apps/poll/urls.py
from django.urls import path
from .views import *
urlpatterns = [
	path('<unique_id>/',polls,name="polls"),
	path('<unique_id>/<int:poll_id>/',poll_page,name="poll_page"),
	path('<unique_id>/voting/<poll_id>/<choice_id>',voting,name="voting"),
	path('<unique_id>/delete/<poll_id>/',delete_poll,name="delete_poll"),
]

guru/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path,include
from django.conf.urls.static import static
from django.contrib.auth import views
from apps.users.forms import UserLoginForm
import notifications.urls
from decouple import config

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', include('apps.basic.urls')),
    path('polls/',include('apps.poll.urls')),
    path('profile/',include('apps.users.urls')),
    path('assignment/', include('apps.assignment.urls')),
    path('announcement/', include('apps.announcement.urls')),
    path('resources/', include('apps.resource.urls')),
    path('classroom/', include('apps.classroom.urls')),
    path('subject/', include('apps.subject.urls')),

    path('accounts/',include('django.contrib.auth.urls')),
    path('rest/',include('rest_framework.urls')),
    path('accounts/', include('allauth.urls')),
    path('comments/', include('django_comments.urls')),
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),
    path('accounts/password_reset/', views.PasswordResetView.as_view(
    html_email_template_name='registration/password_reset_html_email.html',
    extra_email_context={ 'SITE_NAME':settings.SITE_NAME }
    )),
    path('accounts/login/',views.LoginView.as_view(template_name="registration/login.html",
        authentication_form=UserLoginForm),name='login'
    ),  
]

urlpatterns  += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/poll/models.py
from django.db import models
from django.contrib.auth.models import User
from apps.classroom.models import Classroom
from django_quill.fields import QuillField

# Create your models here.
class Poll(models.Model):
	topic = models.CharField(max_length=200)
	choices = [('All Members',"All Members"),('Students','Students')]
	classroom = models.ForeignKey(Classroom,on_delete= models.CASCADE)
	file = models.FileField(upload_to="poll/",null=True,blank = True)
	poll_details = QuillField(null=True,blank=True)
	created_by = models.ForeignKey(User,related_name="poll_by",on_delete=models.DO_NOTHING)
	who_can_vote = models.CharField(choices=choices,max_length=30,default='Students')
	voters = models. ManyToManyField(User,related_name="voters")
	announce_at= models.DateTimeField()

	class Meta:
   		ordering = ['-id']

class Choice(models.Model):
	poll = models.ForeignKey(Poll, on_delete=models.CASCADE)
	choice_text = models.CharField(max_length=200)
	votes = models.IntegerField(default=0)

	def __str__(self):
		return self.choice_text

poll/models.py
from django.db import models
from django.contrib.auth.models import User
from basic.models import Classroom
from django_quill.fields import QuillField

# Create your models here.
class Poll(models.Model):
	topic = models.CharField(max_length=200)
	choices = [('All Members',"All Members"),('Students','Students')]
	classroom = models.ForeignKey(Classroom,on_delete= models.CASCADE)
	file = models.FileField(upload_to="poll/",null=True,blank = True)
	poll_details = QuillField(null=True,blank=True)
	created_by = models.ForeignKey(User,related_name="poll_by",on_delete=models.DO_NOTHING)
	who_can_vote = models.CharField(choices=choices,max_length=30,default='Students')
	voters = models. ManyToManyField(User,related_name="voters")
	announce_at= models.DateTimeField()

	class Meta:
   		ordering = ['-id']

class Choice(models.Model):
	poll = models.ForeignKey(Poll, on_delete=models.CASCADE)
	choice_text = models.CharField(max_length=200)
	votes = models.IntegerField(default=0)

	def __str__(self):
		return self.choice_text

apps/poll/forms.py
from django import forms
from .models import Poll, Choice
from django.conf import settings

class QuestionForm(forms.ModelForm):
	announce_at = forms.DateTimeField(input_formats = settings.DATETIME_INPUT_FORMATS)
	class Meta:
		model = Poll
		fields = ['topic','poll_details','who_can_vote',]

	field_order = ['topic', 'who_can_vote', 'announce_at','poll_details']

class PollUpdateForm(forms.ModelForm):
	class Meta:
		model = Poll
		fields = ['topic','poll_details','announce_at']

	field_order = ['topic', 'announce_at','poll_details']

class ChoiceForm(forms.ModelForm):
	class Meta:
		model = Choice
		fields = ['choice_text']

apps/poll/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse
from django.db.models import *
from django.contrib import messages
from django.http import Http404
from apps.basic.models import *
from apps.utils import members_only
from .forms import *
from .models import *
from django.utils import timezone
from notifications.signals import notify
import datetime

@members_only
@login_required
def polls(request,unique_id,form=None):
	classroom = get_object_or_404(Classroom,unique_id = unique_id)
	polls = Poll.objects.filter(classroom=classroom)
	#handling forms of poll and its choice
	admin_check = classroom.special_permissions.filter(username = request.user.username).exists()
	if admin_check:
		if request.method=='POST':
			form = QuestionForm(request.POST or None,request.FILES)
			datetime_object = datetime.datetime.strptime(request.POST['announce_at'], "%m/%d/%Y %H:%M")
			choice_list = request.POST.getlist('check')
			choice_list = list(filter(filter_fun,choice_list))
			print(form.errors)
			if form.is_valid():
				form = form.save(commit=False)
				form.classroom = classroom
				form.created_by = request.user
				form.announce_at = datetime_object
				form.save()
				for i in choice_list:
					choice=Choice()
					choice.poll = get_object_or_404(Poll,id=form.id)
					choice.choice_text = i
					choice.save()
				verb = f'A poll added/updated in {classroom.class_name}'
				recipients=User.objects.filter(username__in=classroom.members.values_list('username', flat=True))
				url = reverse('poll_page',kwargs={'unique_id':classroom.unique_id,'poll_id':form.id})
				notify.send(sender=request.user,verb=verb,url=url,recipient=recipients)
				return redirect(reverse('polls',kwargs={'unique_id':classroom.unique_id}))
		else:
			form = QuestionForm()

	query,page_range = pagination(request,polls)
	polls=query.object_list
	params = {
		'pollform':form,
		'polls':polls,
		'classroom':classroom,
		'query':query,
		'page_range':page_range,
		'is_admin':admin_check
		}
	return render(request,'poll/polls_list.html',params)

@members_only
@login_required
def poll_page(request,unique_id, poll_id,form=None):
	classroom = get_object_or_404(Classroom,unique_id = unique_id)
	poll = get_object_or_404(Poll,id=poll_id)
	choices = Choice.objects.all().filter(poll=poll)
	time_up = timezone.now() >= poll.announce_at
	if time_up:
		choices = choices.order_by('-votes')

	admin_check = classroom.special_permissions.filter(username = request.user.username).exists()
	if admin_check:
		if request.method=='POST':
			form = PollUpdateForm(request.POST ,request.FILES,instance=poll)
			datetime_object = datetime.datetime.strptime(request.POST['announce_at'], "%m/%d/%Y %H:%M")
			if form.is_valid():
				form = form.save(commit=False)
				form.announce_at = datetime_object
				form.save()
				return redirect(reverse('poll_page',kwargs={'unique_id':classroom.unique_id,'poll_id':poll.id}))
		else:
			form = PollUpdateForm(instance=poll)

	params = {
		'choices' : choices,
		'poll':poll,
		'details':poll.poll_details,
		'classroom':classroom,
		'show_result': time_up or poll.voters.filter(username=request.user.username).exists(),
		'voters_length':poll.voters.count(),
		'updateform':form,
		'is_admin':admin_check,
	}
	if poll.file:
		params['extension']=extension_type(poll.file)
	return render(request,'poll/poll_details.html',params)

@members_only
@login_required
def voting(request,unique_id,poll_id,choice_id):
	classroom = get_object_or_404(Classroom,unique_id = unique_id)
	poll = get_object_or_404(Poll,id=poll_id)
	url = reverse('poll_page',kwargs={'unique_id':classroom.unique_id,'poll_id':poll.id})
	choice = Choice.objects.filter(poll=poll)
	if poll.who_can_vote=='Students':
		teachers = classroom.teacher.all()
		admins = classroom.special_permissions.all()
		if request.user in admins or request.user in teachers:
			messages.add_message(request,messages.INFO,f'Only Students are allowed to Vote.')
			return redirect(url)

	if timezone.now() <= poll.announce_at:
		if poll.voters.filter(username=request.user.username).exists():
			messages.add_message(request,messages.INFO,"You have already voted.")
			return redirect(url)
		else:
			choice=get_object_or_404(Choice,id=choice_id)
			choice.votes += 1
			poll.voters.add(request.user)
			choice.save()
			messages.add_message(request,messages.SUCCESS,'Your choice is recorded.' )
			return redirect(request.META['HTTP_REFERER'])
	else:
		messages.add_message(request,messages.INFO,"Time's up for voting")
		return redirect(url)

@login_required
def delete_poll(request,unique_id, poll_id):
	classroom = get_object_or_404(Classroom,unique_id = unique_id)
	poll = get_object_or_404(Poll,id=poll_id)
	if request.user == poll.created_by:
		poll.delete()
		return redirect(reverse('polls',kwargs={'unique_id':classroom.unique_id}))
	else:
		raise Http404()

poll/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse
from django.db.models import *
from django.contrib import messages
from django.http import Http404
from basic.models import *
from basic.views import member_check
from basic.utils import *
from .forms import *
from .models import *
from django.utils import timezone
from notifications.signals import notify
import datetime

@login_required
def polls(request,unique_id,form=None):
	classroom = get_object_or_404(Classroom,unique_id = unique_id)
	if member_check(request.user,classroom):
		polls = Poll.objects.filter(classroom=classroom)
		#handling forms of poll and its choice
		admin_check = classroom.special_permissions.filter(username = request.user.username).exists()
		if admin_check:
			if request.method=='POST':
				form = QuestionForm(request.POST or None,request.FILES)
				datetime_object = datetime.datetime.strptime(request.POST['announce_at'], "%m/%d/%Y %H:%M")
				choice_list = request.POST.getlist('check')
				choice_list = list(filter(filter_fun,choice_list))
				print(form.errors)
				if form.is_valid():
					form = form.save(commit=False)
					form.classroom = classroom
					form.created_by = request.user
					form.announce_at = datetime_object
					form.save()
					for i in choice_list:
						choice=Choice()
						choice.poll = get_object_or_404(Poll,id=form.id)
						choice.choice_text = i
						choice.save()
					verb = f'A poll added/updated in {classroom.class_name}'
					recipients=User.objects.filter(username__in=classroom.members.values_list('username', flat=True))
					url = reverse('poll_page',kwargs={'unique_id':classroom.unique_id,'poll_id':form.id})
					notify.send(sender=request.user,verb=verb,url=url,recipient=recipients)
					return redirect(reverse('polls',kwargs={'unique_id':classroom.unique_id}))
			else:
				form = QuestionForm()

		query,page_range = pagination(request,polls)
		polls=query.object_list
		params = {
			'pollform':form,
			'polls':polls,
			'classroom':classroom,
			'query':query,
			'page_range':page_range,
			'is_admin':admin_check
			}
		return render(request,'poll/polls_list.html',params)

@login_required
def poll_page(request,unique_id, poll_id,form=None):
	classroom = get_object_or_404(Classroom,unique_id = unique_id)
	poll = get_object_or_404(Poll,id=poll_id)
	if member_check(request.user,classroom):
		choices = Choice.objects.all().filter(poll=poll)
		time_up = timezone.now() >= poll.announce_at
		if time_up:
			choices = choices.order_by('-votes')

		admin_check = classroom.special_permissions.filter(username = request.user.username).exists()
		if admin_check:
			if request.method=='POST':
				form = PollUpdateForm(request.POST ,request.FILES,instance=poll)
				datetime_object = datetime.datetime.strptime(request.POST['announce_at'], "%m/%d/%Y %H:%M")
				if form.is_valid():
					form = form.save(commit=False)
					form.announce_at = datetime_object
					form.save()
					return redirect(reverse('poll_page',kwargs={'unique_id':classroom.unique_id,'poll_id':poll.id}))
			else:
				form = PollUpdateForm(instance=poll)

		params = {
			'choices' : choices,
			'poll':poll,
			'details':poll.poll_details,
			'classroom':classroom,
			'show_result': time_up or poll.voters.filter(username=request.user.username).exists(),
			'voters_length':poll.voters.count(),
			'updateform':form,
			'is_admin':admin_check,
		}
		if poll.file:
			params['extension']=extension_type(poll.file)
		return render(request,'poll/poll_details.html',params)

@login_required
def voting(request,unique_id,poll_id,choice_id):
	classroom = get_object_or_404(Classroom,unique_id = unique_id)
	poll = get_object_or_404(Poll,id=poll_id)
	url = reverse('poll_page',kwargs={'unique_id':classroom.unique_id,'poll_id':poll.id})
	if member_check(request.user,classroom):
		choice = Choice.objects.filter(poll=poll)
		if poll.who_can_vote=='Students':
			teachers = classroom.teacher.all()
			admins = classroom.special_permissions.all()
			if request.user in admins or request.user in teachers:
				messages.add_message(request,messages.INFO,f'Only Students are allowed to Vote.')
				return redirect(url)

		if timezone.now() <= poll.announce_at:
			if poll.voters.filter(username=request.user.username).exists():
				messages.add_message(request,messages.INFO,"You have already voted.")
				return redirect(url)
			else:
				choice=get_object_or_404(Choice,id=choice_id)
				choice.votes += 1
				poll.voters.add(request.user)
				choice.save()
				messages.add_message(request,messages.SUCCESS,'Your choice is recorded.' )
				return redirect(request.META['HTTP_REFERER'])
		else:
			messages.add_message(request,messages.INFO,"Time's up for voting")
			return redirect(url)

@login_required
def delete_poll(request,unique_id, poll_id):
	classroom = get_object_or_404(Classroom,unique_id = unique_id)
	poll = get_object_or_404(Poll,id=poll_id)
	if request.user == poll.created_by:
		poll.delete()
		return redirect(reverse('polls',kwargs={'unique_id':classroom.unique_id}))
	else:
		raise Http404()

templates/poll/poll_details.html
{% extends 'base.html' %} 
{% load filters %}
{% load static %}
{% block title %} POLL DETAILS {% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/polls.css' %}">
{% if is_admin %}
<script src="https://unpkg.com/gijgo@1.9.13/js/gijgo.min.js" type="text/javascript"></script>
<link href="https://unpkg.com/gijgo@1.9.13/css/gijgo.min.css" rel="stylesheet" type="text/css" />
{% include 'django_quill/media.html' %}
{% endif %}
{% endblock %}

{% block content %}
<div>
    {% include 'snippets/navigation.html' %}
    <div class="container-fluid ">
        <div class="row m-0 p-0 container-fluid">
            <div class="col-md-7 mx-auto col-lg-8 col-sm-12">
                {% if is_admin %}
                <button class="btn btn-danger m-1 side-buttons float-right" 
                    style="background:red;" id="userDeleteButton"
                    value="{% url 'delete_poll' classroom.unique_id poll.id %}"> 
					Deletes <i class="fa fa-trash" aria-hidden="true"></i>
                </button>
                {% include 'snippets/deleteconfirm.html' %}
                <a  class="btn m-1 side-buttons float-right" style="background:black;"
                onclick="on(document.getElementsByClassName('overlay')[0])">
                    Update <i class="fas fa-edit"></i>
                </a>
                {% endif %}
                <a  class="btn btn-dark m-1 side-buttons float-right" 
                    href="{% url 'profile' poll.created_by.username %}">
                    Contact <i class="fas fa-phone-volume"></i>
				</a>
                <br><br>
                {% if is_admin %}
                <div class="overlay">
                    <form method="POST" onsubmit="return validate()" class="overlayform"  enctype="multipart/form-data">
                        {% csrf_token %}
                        <a onclick = "off(document.getElementsByClassName('overlay')[0])" id="close"> &times;</a> <br>
                        <h1 class="text-center"> Update</h1><br>
                        <div>
                            {% for field in updateform %}
                            {% if field.field.widget.input_type == 'file' %}
                            <input type="file" name="file" id="actual-btn" hidden/>
                            <label id="file-upload-label" class="text-center"for="actual-btn">
                                Upload File<i class="fa mx-2 fa-upload" aria-hidden="true"></i>
                            </label>
                            {% else %}
                                {{ field.label_tag }}<br>
                                {{ field }}
                            {% endif %}
                            {% endfor %}
                            <input type="submit" class="btn btn-primary float-right"value="Update Poll">
                        </div>
                    </form>
                </div>   
                {% endif %}
                <div style="border-radius:10px;" class=" bg-light mt-4 p-4">
                    {% if poll.file %} 
                        <center>
                            {% if extension == 'image' %}
                                <a href="{{poll.file.url}}">
                                    <img src="{{poll.file.url}}" height="500" width="500">
                                </a>
                            {% elif extension == 'video' %}
                                <video height="300" width="500" controls>
                                    <source src="{{poll.file.url}}">
                                        Your browser does not support the video tag.
                                </video><br>
                                <a href="{{poll.file.url}}" download> Download file</a>
                            {% else %}
                                <a href="{{poll.file.url}}" download> Download file</a> 
                            {% endif %}
                        </center>
                    {% endif %}
                    <h2 class="text-center mx-auto"> {{ poll.topic }} </h2>
                    <div class="ql-editor">{{ details.html|safe }}</div>
                    <div class="divider"></div>
                    <p> {{ poll.who_can_vote }} can participate in this poll.</p>
                    <p style="float:right;"> Vote before {{ poll.announce_at }}</p>
                    <p> {{ voters_length}} Votes.</p>

                    <div class="float-right ">
                        <a style="text-decoration: none;" 
                            target="_blank" 
                            title="invite by whatsapp"
                            href="https://api.whatsapp.com/send?text=Click on
						 	this link {{ request.scheme }}://{{ request.META.HTTP_HOST }}/polls/{{classroom.unique_id}}/poll-page/{{poll.id}}/ 
						 	to participate in poll {{ poll.topic }}/)">
                            <i class="fab fa-whatsapp fa-2x m-2" aria-hidden="true"></i>
                        </a>
                    </div><br><br>
                </div>

                <p id="instruction">
                    Note: You can choose only one option and You can't change once you have voted.
                </p>

                {% for choice in choices %}
                    <a onclick="vote(this)" href="{% url 'voting' classroom.unique_id poll.id choice.id %}">
                        <div class="alert alert-info choice">{{ choice.choice_text}} 
                            {% if show_result %}
                                <span class="text-success float-right">
        							{{ choice.votes }} Votes
        						</span> 
                            {% endif %}
                        </div>
                    </a>
                {% endfor %}
            </div>
        </div>
        
        <div class="container">
            <div class="divider"></div><br>
            {% include 'snippets/comments/poll_comments.html' %}
        </div>
        
    </div>
</div>
{% endblock %}
{% block javascript %}
{% if is_admin %}
<script src="https://unpkg.com/gijgo@1.9.13/js/gijgo.min.js" type="text/javascript"></script>
<script>
    $('#id_announce_at').datetimepicker({
        datepicker: { showOtherMonths: true },
        modal: true,
        footer: true,
        format:'mm/dd/yyyy HH:MM',
		value: '{{ poll.announce_at|date:"m/d/Y" }} {{ poll.announce_at|time:"H:i" }}' 
    });
</script>
{% endif %}
{% endblock %}