apps/assignment/urls.py
from django.urls import path
from . import views
 
urlpatterns = [
    path('<unique_id>/<subject_id>/',views.assignments_list,name="assignments"),
    path('<unique_id>/<subject_id>/<id>/',views.assignment_details,name="assignment_page"),
    path('<unique_id>/<subject_id>/<id>/handle/',views.assignment_handle,name="assignment-handle"),
    path('<unique_id>/<subject_id>/<id>/delete/',views.assignment_delete,name="delete_assignment"),
    path('<unique_id>/<subject_id>/<id>/export-marks',views.export_marks,name="export_marks"),
]

guru/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path,include
from django.conf.urls.static import static
from django.contrib.auth import views
from apps.users.forms import UserLoginForm
import notifications.urls
from decouple import config

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', include('apps.basic.urls')),
    path('polls/',include('apps.poll.urls')),
    path('profile/',include('apps.users.urls')),
    path('assignment/', include('apps.assignment.urls')),
    path('announcement/', include('apps.announcement.urls')),
    path('resources/', include('apps.resource.urls')),
    path('classroom/', include('apps.classroom.urls')),
    path('subject/', include('apps.subject.urls')),

    path('accounts/',include('django.contrib.auth.urls')),
    path('rest/',include('rest_framework.urls')),
    path('accounts/', include('allauth.urls')),
    path('comments/', include('django_comments.urls')),
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),
    path('accounts/password_reset/', views.PasswordResetView.as_view(
    html_email_template_name='registration/password_reset_html_email.html',
    extra_email_context={ 'SITE_NAME':settings.SITE_NAME }
    )),
    path('accounts/login/',views.LoginView.as_view(template_name="registration/login.html",
        authentication_form=UserLoginForm),name='login'
    ),  
]

urlpatterns  += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/assignment/models.py
from django.db import models
from django.contrib.auth.models import User
from django_quill.fields import QuillField
from apps.subject.models import Subject

class Assignment(models.Model):
	subject_name = models.ForeignKey(Subject,on_delete=models.CASCADE)
	uploaded_on = models.DateTimeField(auto_now_add= True)
	file = models.FileField(upload_to="assignments",null=True,blank = True,)
	topic = models.CharField(max_length=100,)
	description = QuillField(null=True,blank=True)
	submission_date = models.DateTimeField() 
	assigned_by = models.ForeignKey(User,on_delete=models.CASCADE)
	submitted_by = models.ManyToManyField(User,related_name="Submissions")
	full_marks = models.IntegerField(default=100)
	submission_link = models.BooleanField(default=True)

	def __str__(self):
		return "Assignment on "+ self.topic

class Submission(models.Model):
	assignment = models.ForeignKey(Assignment, on_delete=models.CASCADE)
	file = models.FileField(upload_to="submissions",)
	submitted_by = models.ForeignKey(User,on_delete=models.CASCADE)
	submitted_on = models.DateTimeField(auto_now_add=True)
	current_status = models.BooleanField(default=False)
	marks_assigned = models.IntegerField(null=True,blank=True)
	history = models.CharField(max_length=5000,null=True,blank=True)
	def __str__(self):
		return "Assignment upload of "+self.assignment.topic + self.submitted_by.username

apps/assignment/forms.py
from django import forms
from django.conf import settings
from .models import Assignment, Submission
from django.forms.widgets import NumberInput

class AssignmentForm(forms.ModelForm):
	submission_date = forms.DateTimeField(input_formats = settings.DATETIME_INPUT_FORMATS)
	class Meta:
		model = Assignment
		fields = ['topic','full_marks','file','description']
		widgets = {
				'full_marks':NumberInput(attrs={'max-value': '100'})
			}
	field_order = ['topic', 'submission_date', 'full_marks','description']

class SubmitAssignmentForm(forms.ModelForm):
	class Meta:
		model = Submission
		fields = ['file']

apps/assignment/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib.auth.models import User
from django.http import Http404, HttpResponse
from django.contrib import messages
from django.db.models import Q
from .forms import AssignmentForm, SubmitAssignmentForm
from .models import Assignment, Submission
from apps.email import email_marks, send_reminder
from apps.delete_notify import assignment_delete_notify
from apps.utils import members_only, pagination, extension_type
from django.urls import reverse
import xlwt, datetime 
from notifications.signals import notify
from django.core.cache import cache
from apps.classroom.models import Classroom
from apps.subject.models import Subject

@members_only
@login_required#checked
def assignments_list(request ,unique_id, subject_id, form=None):
    classroom = get_object_or_404(Classroom,unique_id=unique_id)
    subject = get_object_or_404(Subject,id=subject_id)
    assignments = Assignment.objects.filter(subject_name=subject)
    search = request.GET.get('search')
    if search:
        assignments = assignments.filter(Q(topic__icontains=search)|Q(description__icontains=search))
    query,page_range = pagination(request,assignments)
    assignments=query.object_list

    admin_check = classroom.special_permissions.filter(username = request.user.username).exists()
    is_teacher = admin_check or subject.teacher==request.user

    if is_teacher:
        if request.method=="POST":
            form = AssignmentForm(request.POST,request.FILES)
            datetime_object = datetime.datetime.strptime(request.POST['submission_date'], "%m/%d/%Y %H:%M")
            if form.is_valid():
                assignment = form.save(commit=False)
                assignment.submission_date = datetime_object
                assignment.subject_name = subject
                assignment.assigned_by = request.user
                assignment.save()
                return redirect(request.META['HTTP_REFERER'])
        else:
            form= AssignmentForm()

    params={
        'form':form,
        'subject':subject,
        'classroom':classroom,
        'assignments':assignments,
        'page':query,
        'page_range':page_range,
        }
    return render(request,'assignments/assignment_list.html',params)

@members_only
@login_required#checked
def assignment_details(request,unique_id,subject_id,id):
    updateform = form  = submission = submission_object = None
    classroom = get_object_or_404(Classroom,unique_id=unique_id)
    subject = get_object_or_404(Subject,id=subject_id)
    assignment = get_object_or_404(Assignment,id=id)
    admin_check = classroom.special_permissions.filter(username = request.user.username).exists()
    is_teacher = admin_check or request.user==subject.teacher
    if is_teacher:
        if request.method=="POST":
            updateform = AssignmentForm(request.POST,request.FILES,instance=assignment)
            datetime_object = datetime.datetime.strptime(request.POST['submission_date'], "%m/%d/%Y %H:%M")
            if updateform.is_valid():
                form = updateform.save(commit=False)
                form.submission_date = datetime_object
                form.save()
                return redirect(request.META['HTTP_REFERER'])
        else:
            updateform= AssignmentForm(instance=assignment)
    #submitting assignment
    else: 
        submission_object = Submission.objects.filter(Q(submitted_by=request.user) & Q(assignment=assignment)).first()
        if request.method=="POST":
            if assignment.submission_link:
                form = SubmitAssignmentForm(request.POST, request.FILES,instance=submission_object)
                if(submission_object and submission_object.marks_assigned):
                    messages.add_message(request,messages.WARNING, 'Your assignment is checked, You can\'t change it now')
                    return redirect(request.META['HTTP_REFERER'])
                if form.is_valid():
                    data=form.save(commit=False)
                    data.submitted_by=request.user
                    data.assignment= assignment
                    data.save()
                    assignment.submitted_by.add(request.user)
                    return redirect(request.META['HTTP_REFERER'])
            else:
                messages.add_message(request,messages.WARNING,"Submission link is closed.")
        else:
            form = SubmitAssignmentForm(instance=submission_object)
    
    params={
        'assignment':assignment,
        'extension':extension_type(assignment.file),
        'subject':subject,
        'form':form,
        'updateform':updateform,
        'classroom':classroom,
        'submissionform':form,
        'submission':submission,
        'submission_object':submission_object,
        'is_teacher':is_teacher,
        }       
    return render(request,'assignments/assignment_detail.html',params)

@login_required#checked
def assignment_handle(request,unique_id,subject_id,id):
    classroom = get_object_or_404(Classroom,unique_id=unique_id)
    subject = get_object_or_404(Subject,id=subject_id)
    assignment = get_object_or_404(Assignment,id=id)
    is_teacher = request.user==subject.teacher or request.user == assignment.assigned_by
    
    if is_teacher:
        if request.POST.get('marks_assigned'):
            id  = request.POST.get('id') 
            submission = get_object_or_404(Submission,id=id)
            marks = request.POST.get('marks_assigned')
            submission.marks_assigned = marks
            submission.save()
            url = reverse('assignment_page',kwargs={'unique_id':classroom.unique_id,'subject_id':subject.id,'id':assignment.id})
            messages.add_message(request,messages.SUCCESS,'Marks Assigned.')
            notify.send(sender=request.user,verb=f'You got {marks} for your assignment {assignment.topic}',recipient=submission.submitted_by,url =url)
            email_marks(request,submission,assignment)
            return redirect(reverse('assignment-handle',kwargs={
                'unique_id':classroom.unique_id,
                'subject_id':subject.id,
                'id':assignment.id
                }))

    if request.POST.get('toggle_link'):
        assignment.submission_link  = not assignment.submission_link
        assignment.save()

    #list of submissions
    all_submissions = Submission.objects.filter(assignment=assignment)
    late_submissions = all_submissions.filter(submitted_on__gt=assignment.submission_date)
    ontime_submissions = all_submissions.filter(submitted_on__lte=assignment.submission_date)
    members = classroom.members.all()
    teachers = classroom.teacher.all()
    students = members.difference(teachers).difference(classroom.special_permissions.all())
    submitted = assignment.submitted_by.all()
    not_submitted = students.difference(submitted)
    
    if request.POST.get('send_reminder')=='1':
        #send_notification
        recepients = User.objects.filter(username__in=not_submitted.values_list('username', flat=True))
        url = reverse('assignment_page',kwargs={'unique_id':classroom.unique_id,'subject_id':subject.id,'id':assignment.id})
        notify.send(sender=request.user,verb=f"Reminder to submit your assignment",recipient=recepients,url=url)
        send_reminder(request,assignment,not_submitted.values_list('email', flat=True))

    params = {
        'assignment':assignment,
        'all_submissions':all_submissions,
        'late_submissions':late_submissions,
        'ontime_submissions':ontime_submissions,
        'is_teacher':is_teacher,
        'submitted':submitted,
        'not_submitted':not_submitted,
        'subject':subject,
        'classroom':classroom,
    }
    return render(request,'assignments/assignment_handle.html',params)

@login_required#checked
def assignment_delete(request,unique_id,subject_id,id):
    classroom = get_object_or_404(Classroom,unique_id=unique_id)
    subject = get_object_or_404(Subject,id=subject_id)
    assignment = get_object_or_404(Assignment,id=id)
    admin_check = classroom.special_permissions.filter(username = request.user.username).exists()
    is_teacher = admin_check or request.user==subject.teacher
    if is_teacher:
        assignment.delete()
        assignment_delete_notify(request,assignment)
        return redirect(reverse('assignments',kwargs={'unique_id':classroom.unique_id,'subject_id':subject.id}))
    else:
        raise Http404()

@login_required#checked
def export_marks(request,unique_id,subject_id,id):
    classroom = get_object_or_404(Classroom,unique_id=unique_id)
    admin_check = classroom.special_permissions.filter(username = request.user.username).exists()
    subject = get_object_or_404(Subject,id=subject_id)
    if admin_check or request.user==subject.teacher:
        assignment = get_object_or_404(Assignment,id=id)
        response = HttpResponse(content_type='application/ms-excel')
        response['Content-Disposition'] = f'attachment; filename="mark_sheet of {assignment.topic}.xls"'

        wb = xlwt.Workbook(encoding='utf-8')
        ws = wb.add_sheet('Submissions')
        # Sheet header, first row
        row_num = 0
        font_style = xlwt.XFStyle()
        font_style.font.bold = True
        columns = ['Username','submitted_on','marks_obtained']
        for col_num in range(len(columns)):
            ws.write(row_num, col_num, columns[col_num], font_style)
        # Sheet body, remaining rows
        font_style = xlwt.XFStyle()
        
        rows = Submission.objects.all().filter(assignment=assignment).values_list('submitted_by','submitted_on','marks_assigned')
        rows = [[x.strftime("%Y-%m-%d %H:%M") if isinstance(x, datetime.datetime) else x for x in row] for row in rows ]
        
        for row in rows:
            row_num += 1
            row[0]=str(User.objects.get(id=row[0]))
            for col_num in range(len(row)):

templates/assignments/assignment_detail.html
{% extends 'snippets/subject_page.html' %}
{% load crispy_forms_tags %}
{% block title %} DETAILS {% endblock %}
{% load humanize %}
{% load comments %}
{% load filters %}
{% load static %}
{% block css %}
	<link rel="stylesheet" href="{% static 'css/detailpage.css' %}">
	{% if is_teacher %}
	<script src="https://unpkg.com/gijgo@1.9.13/js/gijgo.min.js" type="text/javascript"></script>
	<link href="https://unpkg.com/gijgo@1.9.13/css/gijgo.min.css" rel="stylesheet" type="text/css" />
	{% include 'django_quill/media.html' %}
	{% endif %}
{% endblock %}

{% block subject_content %}
<div class="container-fluid">
	<div class="row w-100 m-0">
		{% if form and assignment.submission_link %}
		<div class="col-sm-12 col-lg-3 mt-4 order-lg-2">
			<center style="border:4px solid rgb(30, 50, 150);padding:20px;">
				<h2 class="text-center reg-title"> Submit your assignment </h2>
				<form method="POST" onsubmit="return validate()" id="submissionform" enctype="multipart/form-data">{% csrf_token %}
					<input type="file" name="file" id="actual-btn" hidden/>
					<label id="file-upload-label" style="background:rgb(90, 90, 186);width:90%;"for="actual-btn">
						{% if submission_object.file %}
							{{ submission_object.file|filebasename }}. Click to change
						{% else %}
						Upload your assignment
						{% endif %}
					<i class="fa mx-2 fa-upload" aria-hidden="true"></i>
					</label>
					<input type="hidden" name="id" value="{{submission.id }}"><br><br>
					<input type="submit" class="btn btn-primary" value="Hand in">
				</form><br>
			</center>
		</div>

		{% elif not is_teacher and not assignment.submission_link %}
			<div class="col-sm-12 col-lg-3 mt-4 order-lg-2" 
				style="border:3px solid black;float:right;max-height:300px;">
				<h2 class="heading1 text-center text-primary">
					Submission link is closed. Please ask your teacher or admins to open submission link.
				</h2>
			</div>
		{% endif %}

		<div class="col-md-9 mx-lg-auto col-sm-12 order-lg-1">
			<!-- Update assignment logic start -->
			<div class="d-flex flex-wrap justify-content-lg-end justify-content-sm-center ">
				{% if is_teacher %}
				<button class="btn btn-danger mx-1 my-2 buttons" 
					value="{% url 'delete_assignment' classroom.unique_id subject.id assignment.id %}"
					style="background:red;" data-entity="user" id="userDeleteButton">
					Delete <i class="fa fa-trash" aria-hidden="true"></i>
				</button>
				{% include 'snippets/deleteconfirm.html' %}
				
				<button onclick="on(document.getElementsByClassName('overlay')[0])"
					style="background:black;color:white;" class="btn my-2 mx-1 buttons">
						Update <i class="fas fa-edit"></i>
				</button>

				<a href="{% url 'assignment-handle' classroom.unique_id subject.id assignment.id %}"
				style="background:rgb(25, 185, 78);color:white;" class="btn my-2 mx-1 buttons">
					Evaluation<i class="fas fa-edit"></i>
				</a>
			{% endif %}

			<a class="btn btn-dark mx-1 my-2 bg-primary buttons" href="{% url 'profile' assignment.assigned_by %}">
				Contact <i class="fas fa-phone-volume"></i>
			</a>
			</div>
				<!-- Assignment details -->
				<div id="detail-content">
					<p id="detail-topic">
						{{ assignment.topic }}
					</p>
					<b id="submission-date" >
						Submit Before <nobr>{{ assignment.submission_date }}</nobr>
					</b><br>
					{% if assignment.file %} 
						{% if extension == 'image' %}
							<a href="{{assignment.file.url}}">
								<img src="{{assignment.file.url}}" id="media-container">
							</a>
						{% elif extension == 'video' %}
							<video height="300" width="500" id="media-container" controls>
									<source src="{{assignment.file.url}}" type="video/mp4">
									<source src="{{assignment.file.url}}" type="video/ogg">
								Your browser does not support the video tag.
								</video><br>
							<a href="{{assignment.file.url}}" style="text-align: center;" download> Download file</a> 
						{% else %}
							<a href="{{assignment.file.url}}" style="text-align: center;" download> Download file</a> 
						{% endif %} 
					{% endif %}
					<div class="ql-editor">{{ assignment.description.html|safe }}</div>
				</div><br>
				<!-- Assignment details ends -->
				{% include 'snippets/comments/assignmentcomment.html' %}
			</div>
	</div>
</div>

{% if is_teacher %}
	<div class="overlay">
		<form method="POST" id="updateform" class="addForm overlayform" 
			enctype="multipart/form-data">{% csrf_token %}
			<a onclick = "off(document.getElementsByClassName('overlay')[0])" id="close"> &times;</a> <br>
			<h1 class="text-center">Update:{{ assignment }}</h1>
			<div>
				{% for field in updateform %}
					{% if field.field.widget.input_type == 'file' %}
					<input type="file" name="file" id="actual-btn" hidden/>
					<label id="file-upload-label"for="actual-btn">
						{% if assignment.file %}
							{{ assignment.file|filebasename }}. Click to change
						{% else %}
						Upload File
						{% endif %}
					<i class="fa mx-2 fa-upload" aria-hidden="true"></i>
					</label>
					{% else %}
						{{ field.label_tag }}<br>
						{{ field }}
					{% endif %}
				{% endfor %}
				<input type="submit" class="btn btn-primary float-right" value="Update Assignment">
			</div>
		</form>
	</div>
{% endif %}
{% endblock %}
{% block javascript %}
{% if is_teacher %}
<script src="https://unpkg.com/gijgo@1.9.13/js/gijgo.min.js" type="text/javascript"></script>
<script>
	$('#id_submission_date').datetimepicker({
		datepicker: { showOtherMonths: true,calendarWeeks: true },
            modal: true,
			footer: true,
			format:'mm/dd/yyyy HH:MM',
			value: '{{ assignment.submission_date|date:"m/d/Y" }} {{ assignment.submission_date|time:"H:i" }}' 
        });
</script>
{% endif %}
{% endblock %}

templates/assignments/assignment_list.html
{% extends 'snippets/subject_page.html' %} 
{% block title %} ASSIGNMENTS {% endblock %}
{% load humanize %} 
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/listpage.css' %}">
{% if form %}
<script src="https://unpkg.com/gijgo@1.9.13/js/gijgo.min.js" type="text/javascript"></script>
<link href="https://unpkg.com/gijgo@1.9.13/css/gijgo.min.css" rel="stylesheet" type="text/css" />
{% include 'django_quill/media.html' %}
{% endif %}
{% endblock %}

{% block subject_content %}
{% if assignments %}
<div id="search-overlay" class="block">		
	<div class="centered"> 
	  <div id='search-box'>
		<i id="close-btn" class="fa fa-times fa-2x"></i>
		<form  id='search-form' >
		  <input id='search-text' name='search' placeholder='Search' type='text' />
			<button id='search-button' type='submit'><span><i class="fas fa-search"></i></span>
			</button>
		</form>
	  </div>
	</div>
</div>
{% endif %}

<div class="container">
	<div class="row m-2">
		<div class="col-12 d-flex justify-content-between">
			{% if form %}
				<button onclick="on(document.getElementsByClassName('overlay')[0])" 
					type="button" class="btn add-btn float-left">
					Add <i class="fa fa-plus" aria-hidden="true"></i>
				</button>
			{% else %}
			<div></div>
			{% endif %}
			{% if assignments %}
			<div>
				<i id="search-btn" class="fa fa-search fa-2x"></i>
			</div>
			{% endif %}
		</div>
	</div>
 
	{% if form %} 
		<div class="overlay">
		    <form method="POST" onsubmit="return validate()" class="overlayform" enctype="multipart/form-data">
		    	{% csrf_token %}
				<a onclick = "off(document.getElementsByClassName('overlay')[0])" id="close"> &times;</a><br>
				<h1 class="text-center"> Add an assignment </h1>
				<div>
					{% for field in form %}
						{% if field.field.widget.input_type == 'file' %}
						<input type="file" name="file" id="actual-btn" hidden/>
						<label id="file-upload-label"for="actual-btn">
							Upload File<i class="fa mx-2 fa-upload" aria-hidden="true"></i>
						</label>
						{% else %}
							{{ field.label_tag }}<br>
							{{ field }}
						{% endif %}
					{% endfor %}
					<input type="submit" class="btn btn-primary float-right mt-4" value="Add Assignment">
				</div>
			</form>
		</div>
	{% endif %}

	{% if assignments %}
		<div style="min-height:600px;"> 
			{% for assignment in assignments reversed %}
			<div class="container row">
				<div class="col-12">
					<a href="{% url 'assignment_page' classroom.unique_id subject.id assignment.id %}">
				
						<div class="content">
							<div class="topic font-weight-bold">
								<i class="fas fa-briefcase mr-2"></i>{{ assignment.topic }}<br>
							</div>
							<div class="uploaded_by"> Uploaded by: {{ assignment.assigned_by }} </div>
							<div class="time">Submit Before <nobr>{{ assignment.submission_date }}</nobr>
							</div><br>
						</div>
					</a>
				</div>
			</div>
		{% endfor %}
	</div><br> 
		</div>
        {% include 'snippets/paginations.html' %} 
    {% else %}
        <h2 class="no-items">No assignments found !!!</h2>
    {% endif %}
</div>
{% endblock %}

{% block javascript %}
<script src="https://unpkg.com/gijgo@1.9.13/js/gijgo.min.js" type="text/javascript"></script>
<script>
	$('#id_submission_date').datetimepicker({
            datepicker: { showOtherMonths: true,calendarWeeks: true },
            modal: true,
			footer: true,
			format:'mm/dd/yyyy HH:MM',
        });
</script>
{% endblock %}

templates/assignments/assignment_submissions_student.html
{% load crispy_forms_tags %}
<h2 class="reg-title"> Submit your assignment </h2>
<center>
	<form method="POST" id="submissionform" enctype="multipart/form-data">{% csrf_token %}
	    {{form}}<br>
	    <input type="hidden" name="id" value="{{submission.id }}"><br>
		<input type="submit" class="btn btn-primary" value="Hand in">
	</form><br>
</center>